const meals = [
  {
    id: "52767",
    name: "Bakewell tart",
    category: "Dessert",
    area: "British",
    description: "To make the pastry, measure the flour into a bowl and rub in the butter with your fingertips until the mixture resembles fine breadcrumbs. Add the water, mixing to form a soft dough. Roll out the dough and line a tin. Chill, bake blind, spread with raspberry jam, and fill with an almond mixture. Bake until golden.",
    image: "https://www.themealdb.com/images/media/meals/wyrqqq1468233628.jpg",
    price: 7.22,
  },
  {
    id: "52792",
    name: "Bread and Butter Pudding",
    category: "Dessert",
    area: "British",
    description: "Butter bread slices, layer with sultanas and cinnamon. Make a custard with milk, cream, eggs, and sugar. Pour over bread, let soak, and bake until set and golden brown.",
    image: "https://www.themealdb.com/images/media/meals/xqwwpy1483908697.jpg",
    price: 10.18,
  },
  {
    id: "52803",
    name: "Beef Wellington",
    category: "Dinner",
    area: "British",
    description: "Wrap seared beef fillet with mushroom paste and Parma ham, enclose in puff pastry, chill, then bake until golden. Serve with side dishes of your choice.",
    image: "https://www.themealdb.com/images/media/meals/vvpprx1487325699.jpg",
    price: 12.86,
  },
  {
    id: "52807",
    name: "Baingan Bharta",
    category: "Dinner",
    area: "Indian",
    description: "Roast eggplant until soft, mash it, then sauté with onions, tomatoes, and spices. Garnish with coriander and serve with flatbreads.",
    image: "https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",
    price: 14.95,
  },
  {
    id: "52812",
    name: "Beef Brisket Pot Roast",
    category: "Dinner",
    area: "American",
    description: "Sear brisket, cook with onions, garlic, beef stock, and herbs in a Dutch oven until tender. Add carrots, simmer, slice, and serve with gravy.",
    image: "https://www.themealdb.com/images/media/meals/ursuup1487348423.jpg",
    price: 7.6,
  },
  {
    id: "52824",
    name: "Beef Sunday Roast",
    category: "Dinner",
    area: "British",
    description: "Roast beef and potatoes, serve with boiled broccoli and carrots, homemade Yorkshire puddings, and gravy.",
    image: "https://www.themealdb.com/images/media/meals/ssrrrs1503664277.jpg",
    price: 12.19,
  },
  {
    id: "52834",
    name: "Beef Stroganoff",
    category: "Dinner",
    area: "Russian",
    description: "Cook onions and mushrooms, sear beef, combine with crème fraîche, mustard, and beef stock. Serve with pasta or rice.",
    image: "https://www.themealdb.com/images/media/meals/svprys1511176755.jpg",
    price: 13.26,
  },
  {
    id: "52855",
    name: "Banana Pancakes",
    category: "Dessert",
    area: "American",
    description: "Mash banana, mix with eggs, baking powder, and vanilla. Cook small pancakes in a non-stick pan, top with pecans and raspberries.",
    image: "https://www.themealdb.com/images/media/meals/sywswr1511383814.jpg",
    price: 6.28,
  },
  {
    id: "52891",
    name: "Blackberry Fool",
    category: "Dessert",
    area: "British",
    description: "Cook blackberries with sugar, purée, and fold into whipped cream and yogurt. Chill and serve with hazelnut biscuits.",
    image: "https://www.themealdb.com/images/media/meals/rpvptu1511641092.jpg",
    price: 7.48,
  },
  {
    id: "52894",
    name: "Battenberg Cake",
    category: "Dessert",
    area: "British",
    description: "Make almond and pink sponges, cut into strips, assemble in a checkerboard pattern with jam, and wrap in marzipan.",
    image: "https://www.themealdb.com/images/media/meals/ywwrsp1511720277.jpg",
    price: 10.5,
  },
];

export default meals;
